'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QuizCreator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to function ptkurejas_quiz(data) {
        '''    return data;
        '''}
        '''
        '''var quiz_photo_data = jsText();
        '''
        '''for (i = 0; i &lt; quiz_photo_data.answers.length; i++) {
        '''    if (!quiz_photo_data.images[i]) {
        '''        window.external.AddAnswer(quiz_photo_data.answers[i]);
        '''    } else {
        '''        window.external.AddImage(quiz_photo_data.answers[i], quiz_photo_data.images[i]);
        '''    }
        '''}
        '''window.external.
        '''();.
        '''</summary>
        Friend ReadOnly Property open_file_script() As String
            Get
                Return ResourceManager.GetString("open_file_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to function ptkurejas_quiz(photo_data) {
        '''
        '''	var el_prefix = &apos;ptkurejas_el_&apos; + Math.random().toString(36).substr(7) + &apos;_&apos;;
        '''	var iomgs = new Array();
        '''	var n_to_load = 0;
        '''	var count = 0;
        '''	var options_list = &apos;&apos;;
        '''	var cquestion = 0;
        '''	var answers_all_list = new Array();
        '''	var opacity_timer = window.setInterval(opacityMakeBigger, 10);
        '''	var opacity = 0;
        '''	var marquee_top = 0;
        '''
        '''	function id(str) {
        '''		return el_prefix + str;
        '''	}
        '''
        '''	function displayTimer(interval, message, func, func_chk) {
        '''		if (!(!func_chk) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property quiz_core() As String
            Get
                Return ResourceManager.GetString("quiz_core", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
